package views;

import DAO.ProductoDAO;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.Usuario;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ncamp
 */
public class VPrincipalCliente extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipalCliente
     */
    Usuario usuario;
   private List<ProductoSeleccionado> productosSeleccionados;
   
    public VPrincipalCliente(Usuario usuario) {
        initComponents();
        lblNombreCliente.setText(usuario.getNombre());
        cargarTablaProductos();
        this.productosSeleccionados = new ArrayList<>();
        this.usuario= usuario;
    }

    private VPrincipalCliente() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        lblResumen = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido, ");

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        lblResumen.setText("Resumen");

        btnComprar.setText("Comprar ");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnComprar)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblResumen)
                        .addGap(78, 78, 78))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblResumen)
                        .addGap(52, 52, 52)
                        .addComponent(btnComprar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        // TODO add your handling code here:

        finalizarCompra(evt);
    }//GEN-LAST:event_btnComprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPrincipalCliente().setVisible(true);
            }
        });
    }
  private void cargarTablaProductos() {
        ProductoDAO productoDAO = new ProductoDAO();
        DefaultTableModel model = productoDAO.obtenerModeloTablaProductosParaCliente();
        tablaProductos.setModel(model);
        
        // Configurar columnas
        tablaProductos.getColumnModel().getColumn(0).setPreferredWidth(30);  // Checkbox
        tablaProductos.getColumnModel().getColumn(1).setPreferredWidth(40);  // ID
        tablaProductos.getColumnModel().getColumn(2).setPreferredWidth(150); // Nombre
        tablaProductos.getColumnModel().getColumn(3).setPreferredWidth(250); // Descripción
        tablaProductos.getColumnModel().getColumn(4).setPreferredWidth(80);  // Precio
        tablaProductos.getColumnModel().getColumn(5).setPreferredWidth(50);  // Stock
        tablaProductos.getColumnModel().getColumn(6).setPreferredWidth(100); // Categoría
        tablaProductos.getColumnModel().getColumn(7).setPreferredWidth(60);  // Cantidad
        
        // Formatear precio
        tablaProductos.getColumnModel().getColumn(4).setCellRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, 
                boolean isSelected, boolean hasFocus, int row, int column) {
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (value instanceof Integer) {
                    setText(String.format("$%,d", value));
                    setHorizontalAlignment(JLabel.RIGHT);
                }
                return this;
            }
        });
               // Listener para cambios en la tabla
        model.addTableModelListener(e -> {
            if (e.getColumn() == 0 || e.getColumn() == 7) { // Si cambia checkbox o cantidad
                actualizarResumen();
            }
        });


    }
    private void actualizarResumen() {
        productosSeleccionados.clear();
        DefaultTableModel model = (DefaultTableModel) tablaProductos.getModel();
        double total = 0;
        StringBuilder resumen = new StringBuilder("<html>Productos seleccionados:<br>");
        
        for (int i = 0; i < model.getRowCount(); i++) {
            boolean seleccionado = (boolean) model.getValueAt(i, 0);
            if (seleccionado) {
                int id = (int) model.getValueAt(i, 1);
                String nombre = (String) model.getValueAt(i, 2);
                int precio = (int) model.getValueAt(i, 4);
                int cantidad = (int) model.getValueAt(i, 7);
                
                productosSeleccionados.add(new ProductoSeleccionado(id, nombre, precio, cantidad));
                total += precio * cantidad;
                
                resumen.append("- ").append(nombre)
                      .append(" (Cant: ").append(cantidad)
                      .append(", Subtotal: $").append(String.format("%,d", precio * cantidad))
                      .append(")<br>");
            }
        }
        
        resumen.append("<b>Total: $").append(String.format("%,.0f", total)).append("</b></html>");
        lblResumen.setText(resumen.toString());
    }

    private void finalizarCompra(ActionEvent evt) {
        if (productosSeleccionados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione al menos un producto", 
                "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Aquí iría la lógica para procesar la compra
        JOptionPane.showMessageDialog(this, "Compra realizada con éxito\nSeran eviados a: "+usuario.getDireccion()+"\nComprobante enviado: "+usuario.getEmail(), 
            "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }

    // Clase interna para manejar productos seleccionados
    private static class ProductoSeleccionado {
        int id;
        String nombre;
        int precio;
        int cantidad;

        public ProductoSeleccionado(int id, String nombre, int precio, int cantidad) {
            this.id = id;
            this.nombre = nombre;
            this.precio = precio;
            this.cantidad = cantidad;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblResumen;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
